# Site settings
title: Steve Moser
email: contact@stevemoser.org
description: > # this means to ignore newlines until "baseurl:"
  Steve Moser is a Senior Consultant at Levvel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevemoser.org" # the base hostname & protocol for your site - used for feed.xml
twitter_username: stevemoser
github_username:  stevemoser

# Build settings
markdown: kramdown
