# Site settings
title: Steve Moser
email: contact@stevemoser.org
description: > # this means to ignore newlines until "baseurl:"
  Steve Moser is a Senior Consultant at Levvel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stevemoser.org" # the base hostname & protocol for your site - used for feed.xml
twitter_username: stevemoser
github_username:  stevemoser

# Build settings
markdown: kramdown
permalink: /posts/:title.html

relative_links:
  enabled:     true
  collections: true

collections:
  wiki:
    output: true
    permalink: /wiki/:path.html
  
defaults:
  - scope:
      path: ""
      type: wiki
    values:
      layout: page
      
# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-relative-links

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md